/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tijwrxkjqlwlqijjnazg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpandyeGtqcWx3bHFpampuYXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzMjcxMDAsImV4cCI6MjA4MDkwMzEwMH0.C0CWztY5ozXyX8zcy1wKx3E2wZencsnnWNj1KM64P5w"
export const API_BASE = `https://${projectId}.supabase.co/functions/v1/server`
export const STRIPE_API_BASE = `https://${projectId}.supabase.co/functions/v1/stripe`
export const AI_API_BASE = `https://${projectId}.supabase.co/functions/v1/ai`